export const labels = {
  cs: {
    experience: "Zkušenosti",
    skills: "Dovednosti",
    education: "Vzdělání",
    projects: "Projekty",
    languages: "Jazyky",
    profile: "Profil",
    certifications: "Kurzy a certifikace",
    resume: "Životopis",
    coverLetter: "Motivační dopis",
    play: "Hřiště",
    greeting: "Vážený tým,",
    signOff: "S upřímným nadšením,",
    signOffName: "Mario Alina",
    builtBy: "Vytvořil Mario Alina.",
    viewSource: "Zobrazit zdrojový kód",
    comingSoon: "Již brzy",
    getInTouch: "Napište mi",
    askTheAgent: "Zeptej se agenta",
    available: "K dispozici",
    viewResume: "Zobrazit životopis",
    downloadPdf: "Stáhnout PDF",
    openToRoles: "Otevřen nabídkám",
    connect: "Spojme se",
    whyHireMe: "Proč mě najmout?",
    agentRun: "Spustit",
    agentRunning: "Pracuji…",
    agentPlaceholder: "Zeptej se na cokoli o Mariovi — např. Proč bychom tě měli najmout?",
    agentPromptAria: "Otázka pro agenta",
  },
  en: {
    experience: "Experience",
    skills: "Skills",
    education: "Education",
    projects: "Projects",
    languages: "Languages",
    profile: "Profile",
    certifications: "Courses & Certifications",
    resume: "Resume",
    coverLetter: "Cover Letter",
    play: "Play",
    greeting: "To the hiring team —",
    signOff: "With genuine enthusiasm,",
    signOffName: "Mario Alina",
    builtBy: "Built by Mario Alina.",
    viewSource: "View source",
    comingSoon: "Coming soon.",
    getInTouch: "Get in Touch",
    askTheAgent: "Ask the Agent",
    available: "Available for work",
    viewResume: "View résumé",
    downloadPdf: "Download PDF",
    openToRoles: "Open to roles",
    connect: "Connect",
    whyHireMe: "Why hire me?",
    agentRun: "Run agent",
    agentRunning: "Running…",
    agentPlaceholder: "Ask anything about Mario — e.g. Why should we hire you?",
    agentPromptAria: "Question for the agent",
  },
} as const;

export type Labels = (typeof labels)["cs"];
