export const labels = {
  cs: {
    experience: "Zkušenosti",
    skills: "Dovednosti",
    education: "Vzdělání",
    projects: "Projekty",
    languages: "Jazyky",
    profile: "Profil",
    certifications: "Kurzy a certifikace",
    resume: "Životopis",
    coverLetter: "Motivační dopis",
    play: "Hřiště",
    greeting: "Vážený týme Purple LAB,",
    signOff: "S upřímným nadšením,",
    signOffName: "Mario Alina",
    builtBy: "Vytvořil Mario Alina pro Purple LAB.",
    viewSource: "Zobrazit zdrojový kód",
    comingSoon: "Již brzy",
    getInTouch: "Napište mi",
  },
  en: {
    experience: "Experience",
    skills: "Skills",
    education: "Education",
    projects: "Projects",
    languages: "Languages",
    profile: "Profile",
    certifications: "Courses & Certifications",
    resume: "Resume",
    coverLetter: "Cover Letter",
    play: "Play",
    greeting: "To the Purple LAB hiring team —",
    signOff: "With genuine enthusiasm,",
    signOffName: "Mario Alina",
    builtBy: "Built by Mario Alina for Purple LAB.",
    viewSource: "View source",
    comingSoon: "Coming soon.",
    getInTouch: "Get in Touch",
  },
} as const;

export type Labels = typeof labels["cs"];
